[package]
name = "atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
atlas-shared = { path = "../atlas-shared" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.19.0"
groestl = "0.10.1"
base16ct = "0.2.0"
gxhash = "3.4.1"
